// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mffeqkbnweasnorwpbml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mZmVxa2Jud2Vhc25vcndwYm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTEzODUsImV4cCI6MjA2NTYyNzM4NX0.3lHS_yP_CVfG-RQMtKCDfcPOihCoy9bktUtb84dlJGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);